version: "3.7"

services:
  database_transaction:
    image: postgres
    container_name: database_transaction
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transaction
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local