version: "3.7"

services:
  cache:
    image: redis:6.2-alpine
    container_name: cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  db-transaction:
    image: postgres
    container_name: db-transaction
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transaction
    volumes:
      - pgdata:/data/postgres
  api:
    container_name: service--transaction-pismo
    image: service--transaction-pismo
    build: .
    depends_on:
      - cache
      - db-transaction
    ports:
      - "8080:8080"
    environment:
      POSTGRESQL_URL: jdbc:postgresql://db-transaction:5432/transaction
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transaction
      REDIS_HOST: cache
      REDIS_PORT: 6379
    links:
      - db-transaction
      - cache
    volumes:
      - ./:/src

volumes:
  pgdata:
  cache: