INSERT INTO OPERATION(ID, DESCRIPTION)
VALUES (1, 'COMPRA A VISTA');
INSERT INTO OPERATION(ID, DESCRIPTION)
VALUES (2, 'COMPRA PARCELADA');
INSERT INTO OPERATION(ID, DESCRIPTION)
VALUES (3, 'SAQUE');
INSERT INTO OPERATION(ID, DESCRIPTION)
VALUES (4, 'PAGAMENTO');
