INSERT INTO OPERATION(ID, DESCRIPTION) VALUES(1, 'COMPRA A VISTA');
INSERT INTO OPERATION(ID, DESCRIPTION) VALUES(2, 'COMPRA PARCELADA');
INSERT INTO OPERATION(ID, DESCRIPTION) VALUES(3, 'COMPRA SAQUE');
INSERT INTO OPERATION(ID, DESCRIPTION) VALUES(4, 'COMPRA PAGAMENTO');
